apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deployment
  namespace: web
  labels:
    app: tripviewer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registryrnr9881.azurecr.io/tripviewer:v1
        ports:
        - containerPort: 80
        env:
          - name: TRIPS_API_ENDPOINT
            value: http://trips.api.svc.cluster.local
          - name: USERPROFILE_API_ENDPOINT
            value: http://userprofile.api.svc.cluster.local
          - name: ASPNETCORE_ENVIRONMENT
            value: Development

          