apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: poi
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: team.c0e53df537a4392afde.northeurope.aksapp.io
    http:
      paths:
      - path: /api/poi(/|$)(.*)
        pathType: Prefix
        backend:
          service: 
            name: poi
            port: 
              number: 80