# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
  namespace: api
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: 8f70e898-ad77-4f54-8e92-db4296802b36  # Set the clientID of the user-assigned managed identity to use
    keyvaultName: "akst2clukvault01"       # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: sqluser
          objectType: secret              # object types: secret, key, or cert
          objectAlias: SQL_USER
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: sqlpassword
          objectType: secret
          objectAlias: SQL_PASSWORD
          objectVersion: ""
    tenantId: "24e5375a-8837-4d7d-a9d1-ade85deb1535"                # The tenant ID of the key vault