# registryrnr9881.azurecr.io/userjava:v1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userjava-deployment
  namespace: api
  labels:
    app: userjava
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userjava
  template:
    metadata:
      labels:
        app: userjava
    spec:
      containers:
      - name: userjava
        image: registryrnr9881.azurecr.io/userjava:v1
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: SQL_SERVER
            value: sqlserverrnr9881.database.windows.net
      volumes:
        - name: secrets-store01-inline
          csi:
           driver: secrets-store.csi.k8s.io
           readOnly: true
           volumeAttributes:
            secretProviderClass: "azure-kvname-user-msi"