apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  namespace: api
  labels:
    app: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registryrnr9881.azurecr.io/poi:v1
        ports:
        - containerPort: 8080
        env:
        - name: SQL_SERVER
          value: simulatorregistryrnr9881.northeurope.azurecontainer.io
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              key: User
              name: test-secret
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: test-secret