apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  namespace: api
  labels:
    app: poi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registryrnr9881.azurecr.io/poi:v1
        ports:
        - containerPort: 8080
        env:
<<<<<<< HEAD
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: SQL_SERVER
            value: sqlserverrnr9881.database.windows.net
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: test-secret
                key: password
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: test-secret
                key: User
           
              
=======
        - name: SQL_SERVER
          value: simulatorregistryrnr9881.northeurope.azurecontainer.io
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              key: User
              name: test-secret
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: test-secret
>>>>>>> c69bac548d99eb1223415ef80374e483eed75043
