apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  namespace: api
  labels:
    app: poi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registryrnr9881.azurecr.io/poi:v1
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        env:
        - name: SQL_SERVER
          value: sqlserverrnr9881.database.windows.net
      volumes:
        - name: secrets-store01-inline
          csi:
           driver: secrets-store.csi.k8s.io
           readOnly: true
           volumeAttributes:
            secretProviderClass: "azure-kvname-user-msi"