apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-deployment
  namespace: api
  labels: 
    app: userprofile
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: registryrnr9881.azurecr.io/userprofile:v1
        ports:
        - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: SQL_SERVER
            value: sqlserverrnr9881.database.windows.net
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: test-secret
                key: password
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: test-secret
                key: User

